# Análise de Tópicos — Discursos dos Presidentes do Brasil

Este notebook usa IA, especificamente BERTopic, para extrair informações gerais sobre quais assuntos são abordados em cada discurso.

## Configuração Inicial:

No projeto, foi utizado **pandas**, **BERTopic** e **POSTGRESQL**.

In [149]:
import pandas as pd
import os

from bertopic import BERTopic
from sqlalchemy import create_engine
from dotenv import load_dotenv

load_dotenv() # configurar .env para conectar ao database do postgres

DB_HOST = os.getenv("DB_HOST")
DB_PORT = os.getenv("DB_PORT")
DB_NAME = os.getenv("DB_NAME")
DB_USER = os.getenv("DB_USER")
DB_PASSWORD = os.getenv("DB_PASSWORD")

engine = create_engine(
    f"postgresql+psycopg2://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}"
)

query = """
SELECT presidente, n_par, par
FROM speeches;
"""

df = pd.read_sql(query, engine)
df.head()

,presidente,n_par,par
0,Marechal Deodoro da Fonseca,1,"Concidadãos – O povo, o exército e a armada na..."
1,Marechal Deodoro da Fonseca,2,Como resultado imediato desta revolução nacion...
2,Marechal Deodoro da Fonseca,3,"Para comporem esse governo, enquanto a nação s..."
3,Marechal Deodoro da Fonseca,4,"Concidadãos – O governo provisório, simples ag..."
4,Marechal Deodoro da Fonseca,5,No uso das atribuições e faculdades extraordin...

In [158]:
presidentes_republica_velha = [
    "Marechal Deodoro da Fonseca",
    "Floriano Peixoto",
    "Prudente de Morais",
    "Campos Sales",
    "Rodrigues Alves",
    "Affonso Pena",
    "Nilo Peçanha",
    "Hermes da Fonseca",
    "Wenceslau Brás",
    "Epitácio Pessoa",
    "Arthur Bernardes",
    "Washington Luís"
]

Republica_Velha = df[df['presidente'].isin(presidentes_republica_velha)]['par'].tolist()
Todos = df['par'].tolist()

topic_model = BERTopic(embedding_model="paraphrase-multilingual-mpnet-base-v2",min_topic_size=3)

In [159]:
topics, probs = topic_model.fit_transform(Todos)
topic_model.get_topic_info().head(10)

,Topic,Count,Name,Representation,Representative_Docs
0,-1,507,-1_que_de_do_da,"[que, de, do, da, mais, com, em, para, os, dos]",[O Brasil honra sempre na devida conta e é mui...
1,0,35,0_estado_não_públicos_justiça,"[estado, não, públicos, justiça, há, se, ser, ...","[No meio dessas delicadas obrigações, que torn..."
2,1,29,1_me_dever_soldado_desempenho,"[me, dever, soldado, desempenho, responsabilid...","[Como quer que seja, afirmarei desde já que é ..."
3,2,27,2_moeda_financeira_dívida_1899,"[moeda, financeira, dívida, 1899, fiscal, sobr...",[Temos de lutar para que os anos noventa resta...
4,3,26,3_amazônia_país_ambiental_desenvolvimento,"[amazônia, país, ambiental, desenvolvimento, i...","[Hoje, tantas áreas do país estão devidamente ..."
5,4,24,4_queridos_brasileiras_queridas_brasileiros,"[queridos, brasileiras, queridas, brasileiros,...",[Queridos e queridas brasileiras e brasileiros...
6,5,21,5_em_regime_1934_político,"[em, regime, 1934, político, constituição, con...","[Fora daí, em vez de poderes coordenados não t..."
7,6,20,6_mudar_ousadia_nossa_semeador,"[mudar, ousadia, nossa, semeador, avançar, sem...","[Sim, neste momento, ao invés de simplesmente ..."
8,7,20,7_república_cargo_presidência_me,"[república, cargo, presidência, me, da, excelê...",[Assumo a Presidência da República consciente ...
9,8,20,8_nunca_brasileiros_tantos_pobreza,"[nunca, brasileiros, tantos, pobreza, tanta, d...",[Nunca tantos brasileiros ascenderam às classe...

In [160]:
topic_model.get_topic_info()

,Topic,Count,Name,Representation,Representative_Docs
0,-1,507,-1_que_de_do_da,"[que, de, do, da, mais, com, em, para, os, dos]",[O Brasil honra sempre na devida conta e é mui...
1,0,35,0_estado_não_públicos_justiça,"[estado, não, públicos, justiça, há, se, ser, ...","[No meio dessas delicadas obrigações, que torn..."
2,1,29,1_me_dever_soldado_desempenho,"[me, dever, soldado, desempenho, responsabilid...","[Como quer que seja, afirmarei desde já que é ..."
3,2,27,2_moeda_financeira_dívida_1899,"[moeda, financeira, dívida, 1899, fiscal, sobr...",[Temos de lutar para que os anos noventa resta...
4,3,26,3_amazônia_país_ambiental_desenvolvimento,"[amazônia, país, ambiental, desenvolvimento, i...","[Hoje, tantas áreas do país estão devidamente ..."
...,...,...,...,...,...
103,102,3,102_estrangeiro_capital_vasto_daí,"[estrangeiro, capital, vasto, daí, capitais, i...","[Por outro lado, essas realizações exigem que ..."
104,103,3,103_desdobrar_afirmar_republicano_teve,"[desdobrar, afirmar, republicano, teve, deplor...","[Nada me cumpre acrescentar, no momento em que..."
105,104,3,104_indústrias_aflitiva_ajuizar_acrescento,"[indústrias, aflitiva, ajuizar, acrescento, ap...",[Para que não sobre a uns poucos o que a muito...
106,105,3,105_cidadania_governar_poderosas_exercido,"[cidadania, governar, poderosas, exercido, esf...","[Os direitos e interesses da população, o fort..."
107,106,3,106_reafirmo_gozo_inegociável_descansarei,"[reafirmo, gozo, inegociável, descansarei, ins...",[Reafirmo meu compromisso de construir uma soc...